---
- name: Install Google Chrome repo
  become_user: root
  copy:
    src: google-chrome.repo
    dest: /etc/yum.repos.d/
    force: yes
    owner: root
    group: root
    mode: 644

- name: Import Google Chrome signing key
  become_user: root
  rpm_key:
    key: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present

- name: Install Google Chrome
  become_user: root
  dnf:
    name: google-chrome-stable
    state: present
