---
- name: Upgrade existed packages
  become_user: root
  dnf:
    name: "*"
    state: latest

- name: Install core packages
  become_user: root
  dnf:
    name: "{{ item }}"
    state: installed
  with_items:
    - git
    - tar
    - util-linux-user
    - vim
    - zsh

- include: google-chrome.yml