# VM
cpus: 2
memory: 4096
bridge: false
mounts:
  - name: work
    description: personal working directory
    path: c:/work
  - name: dropbox
    description: Dropbox directory
    path: $HOME/Dropbox

# Provisioning
dotfiles: https://github.com/ubnt-intrepid/dotfiles.git
ansible: true
skip_tags:
  - huge
