# vim: set ft=yaml ts=2 sw=2 et :

# VM
mount:
  - { name: work    , path: "c:/work" }
  - { name: dropbox , path: "$HOME/Dropbox" }
network:
  - { type: bridge }

# Provisioning
dotfiles: https://github.com/ubnt-intrepid/dotfiles.git
skip_tags: [ 'huge' ]
