dotfiles: https://github.com/ubnt-intrepid/dotfiles.git
mounts:
  - name: work
    description: personal working directory
    path: c:/work
  - name: dropbox
    description: Dropbox directory
    path: $HOME/Dropbox
memory: 4096
cpus: 2
run_ansible: false
enable_bridge: true
