filetype off
filetype plugin indent off

" Clear all GUI options
set guioptions=

" Font configuration
if has('win32') || has('win64')
  " set guifont=Iosevka_Term:h13
  set guifont=CicaE:h13
  set guifontwide=HGｺﾞｼｯｸM:h13
  set renderoptions=type:directx,renmode:5
else
  set guifont=Ubuntu\ Mono\ 14
endif

set iminsert=0
set imsearch=0

" set t_Co=256

filetype plugin indent on
