---
- name: Install utility packages
  become_user: root
  dnf:
    name: "{{ item }}"
    state: installed
  with_items:
    - golang
    - ncurses-devel

- name: Install fzf
  shell: env GOPATH=$HOME/.go go get -v github.com/junegunn/fzf/src/fzf
  args:
    creates: "$HOME/.go/bin/fzf"