# vim: set ft=zsh ts=2 sw=2 et :

### Load preludes
source "$HOME/.zsh.d/prelude.zsh"

### Load Plugins
source "$HOME/.zsh.d/plugin.zsh"

### Load user configurations
source "$HOME/.zsh.d/prompt.zsh"
source "$HOME/.zsh.d/keybind.zsh"
source "$HOME/.zsh.d/alias.zsh"
source "$HOME/.zsh.d/repos.zsh"
source "$HOME/.zsh.d/misc.zsh"

### Local settings
if [[ -s "$HOME/.zshrc.local" ]]; then
  source "$HOME/.zshrc.local"
fi
