#!/bin/zsh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# VNC tools
xsetroot -solid grey
vncconfig -iconic &

# IME configuration
export GTK_IM_MODULE='uim'
export QT_IM_MODULE='uim'
export XMODIFIERS="@im=uim"
(( $+commands[uim-xim] )) && (uim-xim &) || true
(( $+commands[uim-toolbar-gtk3-systray] )) && (uim-toolbar-gtk3-systray &) || true

# start session.
(( $+commands[xfce4-session] )) && exec xfce4-session
